import { AnimeMedia } from '@shared/anime';

// Fallback data to use when JIKAN API is unavailable
export const fallbackAnimeData: AnimeMedia[] = [
  {
    id: 'fallback-1',
    title: 'Attack on Titan',
    titleEnglish: 'Attack on Titan',
    titleJapanese: '進撃の巨人',
    description: 'Humanity fights for survival against giant humanoid Titans.',
    synopsis: 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls.',
    type: 'anime',
    status: 'completed',
    genres: ['Action', 'Drama', 'Fantasy', 'Horror'],
    releaseYear: 2013,
    endYear: 2023,
    episodes: 87,
    seasons: 4,
    duration: 24,
    rating: 9.0,
    popularity: 1,
    coverImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=600&fit=crop&crop=faces',
    bannerImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=400&fit=crop',
    trailer: 'MGRm4IzK1SQ',
    studio: 'Studio Pierrot',
    director: 'Tetsuro Araki',
    source: 'Manga',
    platforms: ['Crunchyroll', 'Funimation', 'Hulu', 'Netflix'],
    tags: ['Military', 'Post-Apocalyptic', 'Survival', 'Tragedy'],
    ageRating: 'TV-MA',
    malScore: 9.0
  },
  {
    id: 'fallback-2',
    title: 'One Piece',
    titleEnglish: 'One Piece',
    titleJapanese: 'ワンピース',
    description: 'Follow Monkey D. Luffy and his pirate crew in search of the ultimate treasure.',
    synopsis: 'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line.',
    type: 'anime',
    status: 'airing',
    genres: ['Action', 'Adventure', 'Comedy', 'Drama'],
    releaseYear: 1999,
    episodes: 1000,
    seasons: 21,
    duration: 24,
    rating: 9.2,
    popularity: 2,
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&h=600&fit=crop&crop=faces',
    bannerImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop',
    trailer: 'Ades3pQbeh8',
    studio: 'Toei Animation',
    director: 'Eiichiro Oda',
    source: 'Manga',
    platforms: ['Crunchyroll', 'Funimation', 'Netflix'],
    tags: ['Pirates', 'Friendship', 'Adventure', 'Shounen'],
    ageRating: 'TV-14',
    malScore: 9.2
  },
  {
    id: 'fallback-3',
    title: 'Demon Slayer',
    titleEnglish: 'Demon Slayer: Kimetsu no Yaiba',
    titleJapanese: '鬼滅の刃',
    description: 'A young boy becomes a demon slayer to avenge his family.',
    synopsis: 'Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado\'s shoulders.',
    type: 'anime',
    status: 'airing',
    genres: ['Action', 'Supernatural', 'Historical'],
    releaseYear: 2019,
    episodes: 44,
    seasons: 3,
    duration: 24,
    rating: 8.7,
    popularity: 3,
    coverImage: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=400&h=600&fit=crop&crop=faces',
    bannerImage: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=1200&h=400&fit=crop',
    trailer: 'VQGCKyvzIM4',
    studio: 'Ufotable',
    director: 'Haruo Sotozaki',
    source: 'Manga',
    platforms: ['Crunchyroll', 'Funimation', 'Netflix', 'Hulu'],
    tags: ['Demons', 'Family', 'Sword Fighting', 'Shounen'],
    ageRating: 'TV-14',
    malScore: 8.7
  },
  {
    id: 'fallback-4',
    title: 'Jujutsu Kaisen',
    titleEnglish: 'Jujutsu Kaisen',
    titleJapanese: '呪術廻戦',
    description: 'A student joins sorcerers to eliminate cursed spirits.',
    synopsis: 'Although Yuji Itadori looks like your average teenager, his immense physical strength is something to behold!',
    type: 'anime',
    status: 'airing',
    genres: ['Action', 'Supernatural', 'School'],
    releaseYear: 2020,
    episodes: 24,
    seasons: 2,
    duration: 24,
    rating: 8.8,
    popularity: 5,
    coverImage: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400&h=600&fit=crop&crop=faces',
    bannerImage: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1200&h=400&fit=crop',
    trailer: '4A_X-Dvl0ws',
    studio: 'MAPPA',
    director: 'Sunghoo Park',
    source: 'Manga',
    platforms: ['Crunchyroll', 'Funimation'],
    tags: ['Curses', 'School', 'Dark Fantasy', 'Shounen'],
    ageRating: 'TV-14',
    malScore: 8.8
  },
  {
    id: 'fallback-5',
    title: 'My Hero Academia',
    titleEnglish: 'My Hero Academia',
    titleJapanese: '僕のヒーローアカデミア',
    description: 'In a world where most people have superpowers, a powerless boy enrolls in a hero academy.',
    synopsis: 'The appearance of "quirks," newly discovered super powers, has been steadily increasing over the years.',
    type: 'anime',
    status: 'airing',
    genres: ['Action', 'Adventure', 'School', 'Supernatural'],
    releaseYear: 2016,
    episodes: 138,
    seasons: 6,
    duration: 24,
    rating: 8.5,
    popularity: 4,
    coverImage: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400&h=600&fit=crop&crop=faces',
    bannerImage: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=1200&h=400&fit=crop',
    trailer: 'D5fYOnwYkj4',
    studio: 'Studio Bones',
    director: 'Kenji Nagasaki',
    source: 'Manga',
    platforms: ['Crunchyroll', 'Funimation', 'Hulu'],
    tags: ['Heroes', 'School', 'Superpowers', 'Shounen'],
    ageRating: 'TV-14',
    malScore: 8.5
  },
  {
    id: 'fallback-6',
    title: 'Death Note',
    titleEnglish: 'Death Note',
    titleJapanese: 'デスノート',
    description: 'A high school student finds a supernatural notebook that grants the power to kill.',
    synopsis: 'A shinigami, as a god of death, can kill any person—provided they see their victim\'s face and write their victim\'s name in a notebook called a Death Note.',
    type: 'anime',
    status: 'completed',
    genres: ['Psychological', 'Supernatural', 'Thriller'],
    releaseYear: 2006,
    episodes: 37,
    seasons: 1,
    duration: 24,
    rating: 9.0,
    popularity: 6,
    coverImage: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=600&fit=crop&crop=faces',
    bannerImage: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&h=400&fit=crop',
    trailer: 'NlJZ-YgAt-c',
    studio: 'Madhouse',
    director: 'Tetsuro Araki',
    source: 'Manga',
    platforms: ['Crunchyroll', 'Netflix'],
    tags: ['Death', 'Psychological', 'Mind Games', 'Drama'],
    ageRating: 'TV-14',
    malScore: 9.0
  }
];
